#!/usr/bin/env python3
"""
Generate zenodo-works.bib from the minted DOI map.

WHY THIS EXISTS. Adding works to an ORCID record over the API requires the ORCID
**Member API** and the `/activities/update` scope, which are available only to
paying ORCID member organisations. The free Public API is read-only, and there is
no personal write token — so an individual researcher cannot script their own
ORCID record, and neither can anyone acting for them.

The free routes are therefore:

  1. DataCite Auto-Update  — best, and ongoing. Enable it once in DataCite
     Profiles and every future DOI carrying the ORCID lands automatically.
     ⚠️ It only fires for DOIs registered or updated AFTER it is enabled, so it
     does not backfill records minted earlier. See scripts/zenodo-touch.py.
  2. DataCite Commons      — manual "Add to ORCID Record" per DOI.
  3. This file             — ORCID: Add works -> Add BibTeX -> select it.

Route 3 needs no third-party service and no permissions, which is why it is the
one generated here.

    ./scripts/make-bibtex.py [--dir defensive-publications]
"""

import argparse
import importlib.util
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent

_spec = importlib.util.spec_from_file_location("zd", ROOT / "scripts/zenodo-deposit.py")
zd = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(zd)


def bib_escape(s):
    # '&' and '%' are BibTeX control characters; emphasis markers are noise here.
    s = re.sub(r"[*`]", "", s)
    return s.replace("\\", "").replace("&", r"\&").replace("%", r"\%")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", action="append", default=None)
    ap.add_argument("--out", default="zenodo-works.bib")
    # CONCEPT DOIs BY DEFAULT. A concept doi always resolves to the newest
    # version; a version doi goes stale the moment the paper is revised. This was
    # opt-in via --concept and the default bit us: the 63 works imported into ORCID
    # carry concept dois, but the committed zenodo-works.bib had been regenerated
    # without the flag and held version dois. Re-importing that file would have
    # added 64 works that group with nothing — a duplicate corpus. The safe form is
    # the default; --version-doi is the deliberate opt-out.
    ap.add_argument("--version-doi", action="store_true",
                    help="emit the VERSION doi instead of the concept doi. Rarely "
                         "wanted: it pins a citation to one revision.")
    ap.add_argument("--concept", action="store_true",
                    help=argparse.SUPPRESS)   # now the default; kept so old invocations still work
    args = ap.parse_args()
    dirs = args.dir or list(zd.DIRS)

    dois = json.loads((ROOT / "zenodo-dois.json").read_text())
    lines = [
        "% Zenodo DOIs for the THonly research corpus.",
        "% Import into ORCID: Add works -> Add BibTeX -> select this file.",
        "% Generated by scripts/make-bibtex.py from zenodo-dois.json — do not hand-edit.",
        "",
    ]

    n = 0
    for slug, v in sorted(dois.items()):
        doi = (v.get("doi") if args.version_doi else v.get("concept_doi")) or v.get("doi")
        if not v.get("published") or not doi:
            continue
        path = next((ROOT / d / f"{slug}.md" for d in dirs
                     if (ROOT / d / f"{slug}.md").exists()), None)
        if path is None:
            continue

        fm = zd.frontmatter(path.read_text())
        # TITLE ONLY — the subtitle is deliberately NOT appended. This corpus's
        # house style makes `subtitle` an abstract-length enumeration of the
        # claimed mechanisms (the longest runs to ~430 characters), which is
        # correct on the paper and ruinous in a BibTeX title field: ORCID renders
        # it verbatim, so 48 of 64 works displayed a half-page title. Matches
        # zenodo-deposit.py build_metadata(), which titles the record with `title`
        # alone and puts the subtitle at the head of the description instead.
        title = fm.get("title", slug)
        # Double braces protect the corpus's deliberate capitalisation and its
        # Pali/Khmer diacritics from BibTeX's title-casing.
        title = bib_escape(title)

        authors = []
        for a in re.split(r"[·,]", fm.get("authors", "Thon Ly")):
            a = a.strip().replace("℠", "").replace("®", "").strip()
            if a:
                authors.append(zd.CREATORS.get(a, {}).get("cite_as", a))

        kind = zd.DOC_TYPE.get(path.parent.name, "publication")
        lines += [
            f"@misc{{{slug},",
            f"  title        = {{{{{title}}}}},",
            f"  author       = {{{' and '.join(authors)}}},",
            f"  year         = {{{(fm.get('date') or '2026')[:4]}}},",
            "  publisher    = {Zenodo},",
            f"  doi          = {{{doi}}},",
            f"  url          = {{https://doi.org/{doi}}},",
            f"  howpublished = {{{kind.capitalize()}, THonly research corpus}},",
            f"  note         = {{CC0 1.0. Canonical: https://thonly.org/research/{slug}}}",
            "}\n",
        ]
        n += 1

    (ROOT / args.out).write_text("\n".join(lines))
    print(f"wrote {args.out} — {n} entries from {', '.join(dirs)} "
          f"using {'VERSION' if args.version_doi else 'CONCEPT'} DOIs")


if __name__ == "__main__":
    main()
