#!/usr/bin/env python3
"""
Generate zenodo-works.bib from the minted DOI map.

WHY THIS EXISTS. Adding works to an ORCID record over the API requires the ORCID
**Member API** and the `/activities/update` scope, which are available only to
paying ORCID member organisations. The free Public API is read-only, and there is
no personal write token — so an individual researcher cannot script their own
ORCID record, and neither can anyone acting for them.

The free routes are therefore:

  1. DataCite Auto-Update  — best, and ongoing. Enable it once in DataCite
     Profiles and every future DOI carrying the ORCID lands automatically.
     ⚠️ It only fires for DOIs registered or updated AFTER it is enabled, so it
     does not backfill records minted earlier. See scripts/zenodo-touch.py.
  2. DataCite Commons      — manual "Add to ORCID Record" per DOI.
  3. This file             — ORCID: Add works -> Add BibTeX -> select it.

Route 3 needs no third-party service and no permissions, which is why it is the
one generated here.

    ./scripts/make-bibtex.py [--dir defensive-publications]
"""

import argparse
import importlib.util
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent

_spec = importlib.util.spec_from_file_location("zd", ROOT / "scripts/zenodo-deposit.py")
zd = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(zd)


def bib_escape(s):
    # '&' and '%' are BibTeX control characters; emphasis markers are noise here.
    s = re.sub(r"[*`]", "", s)
    return s.replace("\\", "").replace("&", r"\&").replace("%", r"\%")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", action="append", default=None)
    ap.add_argument("--out", default="zenodo-works.bib")
    ap.add_argument("--concept", action="store_true",
                    help="use the CONCEPT doi (always resolves to the newest "
                         "version) instead of the version doi. Preferred for an "
                         "ORCID profile: a version doi goes stale the moment the "
                         "paper is revised, and each revision adds another entry.")
    args = ap.parse_args()
    dirs = args.dir or list(zd.DIRS)

    dois = json.loads((ROOT / "zenodo-dois.json").read_text())
    lines = [
        "% Zenodo DOIs for the THonly research corpus.",
        "% Import into ORCID: Add works -> Add BibTeX -> select this file.",
        "% Generated by scripts/make-bibtex.py from zenodo-dois.json — do not hand-edit.",
        "",
    ]

    n = 0
    for slug, v in sorted(dois.items()):
        doi = (v.get("concept_doi") if args.concept else v.get("doi")) or v.get("doi")
        if not v.get("published") or not doi:
            continue
        path = next((ROOT / d / f"{slug}.md" for d in dirs
                     if (ROOT / d / f"{slug}.md").exists()), None)
        if path is None:
            continue

        fm = zd.frontmatter(path.read_text())
        title = fm.get("title", slug)
        if fm.get("subtitle"):
            title = f"{title}: {fm['subtitle']}"
        # Double braces protect the corpus's deliberate capitalisation and its
        # Pali/Khmer diacritics from BibTeX's title-casing.
        title = bib_escape(title)

        authors = []
        for a in re.split(r"[·,]", fm.get("authors", "Thon Ly")):
            a = a.strip().replace("℠", "").replace("®", "").strip()
            if a:
                authors.append(zd.CREATORS.get(a, {}).get("cite_as", a))

        kind = zd.DOC_TYPE.get(path.parent.name, "publication")
        lines += [
            f"@misc{{{slug},",
            f"  title        = {{{{{title}}}}},",
            f"  author       = {{{' and '.join(authors)}}},",
            f"  year         = {{{(fm.get('date') or '2026')[:4]}}},",
            "  publisher    = {Zenodo},",
            f"  doi          = {{{doi}}},",
            f"  url          = {{https://doi.org/{doi}}},",
            f"  howpublished = {{{kind.capitalize()}, THonly research corpus}},",
            f"  note         = {{CC0 1.0. Canonical: https://thonly.org/research/{slug}}}",
            "}\n",
        ]
        n += 1

    (ROOT / args.out).write_text("\n".join(lines))
    print(f"wrote {args.out} — {n} entries from {', '.join(dirs)} "
          f"using {'CONCEPT' if args.concept else 'VERSION'} DOIs")


if __name__ == "__main__":
    main()
